[package]
name = "package-manager"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "package-manager"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
package-trust = { path = "../package-trust" }
save-vault = { path = "../save-vault" }
