[package]
name = "sim-host-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
device-profile = { path = "../device-profile" }
png.workspace = true
sdl2 = { workspace = true, features = ["ttf"] }
serde.workspace = true
serde_json.workspace = true
sim-domain = { path = "../domain" }
launcher-presentation = { path = "../launcher-presentation" }
settings-ui = { path = "../settings-ui" }
sim-platform-contract = { path = "../platform-contract" }
wifi-manager = { path = "../wifi-manager" }
wifi-settings-controller = { path = "../wifi-settings-controller" }
ui-model = { path = "../ui-model" }
